// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import LoginModal from "@/components/LoginModal";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { AuthProvider } from "@/contexts/AuthContext";
import { LoginModalProvider } from "@/contexts/LoginModalContext";
import { ProductProvider } from "@/contexts/ProductContext";
import { FavoritesProvider } from "@/contexts/FavoritesContext";
import { CartProvider } from "@/contexts/CartContext";

const interFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body className={`${interFont.className} antialiased max-w-screen overflow-x-hidden`}>
        <AuthProvider>
          <LoginModalProvider>
            <ProductProvider>
              <FavoritesProvider>
                <CartProvider>
                  <Navbar />
                  {children}
                  <LoginModal />
                  <ToastContainer
                    position="top-right"
                    autoClose={2000}
                    hideProgressBar
                    newestOnTop={false}
                    closeOnClick
                    rtl={false}
                    pauseOnFocusLoss
                    draggable
                    pauseOnHover
                  />
                </CartProvider>
              </FavoritesProvider>
            </ProductProvider>
          </LoginModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
